apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: rideflow
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
