apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ride-request-service-hpa
  namespace: rideflow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ride-request-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60